# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MyItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(230, 57)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.num = QtWidgets.QLabel(Form)
        self.num.setObjectName("num")
        self.horizontalLayout.addWidget(self.num)
        self.title = QtWidgets.QLabel(Form)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.value = QtWidgets.QLabel(Form)
        # self.value.setText("")
        # self.value.setPixmap(QtGui.QPixmap(":/img/img/title.png"))
        self.value.setObjectName("value")
        self.horizontalLayout.addWidget(self.value)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.num.setText(_translate("Form", "1"))
        self.title.setText(_translate("Form", "wzl"))
import img_rc
